---
- name: Common | Update apt cache
  become: true
  apt: update-cache=yes
  tags: common

- name: Common | Install System Packages
  become: true
  apt: pkg={{ item }} state=installed
  with_items: "{{ system_packages }}"
  tags: common

- name: Common | Configure PALANTIR_ENVIRONMENT variable
  lineinfile: dest=/home/vagrant/.profile state=present line='export PALANTIR_ENVIRONMENT="vagrant"'
  tags: common

- name: Common | Copy user's gitconfig from host
  copy: src=~/.gitconfig dest=/home/vagrant/.gitconfig
  tags: common

- name: Common | Get user.name from host's gitconfig
  git_config:
    name: user.name
    scope: global
  register: git_author_name
  tags: common

- name: Common | Get user.email from host's gitconfig
  git_config:
    name: user.email
    scope: global
  register: git_author_email
  tags: common
  
- name: Common | Copy gitconfig from template
  template:
    src: gitconfig
    dest: /home/vagrant/.gitconfig

- name: Common | Copy gitignore
  copy: src=roles/common/templates/gitignore dest=/home/vagrant/.gitignore
  tags: common

- name: Common | Configure global gitignore
  command: /usr/bin/git config --global core.excludesfile ~/.gitignore
  tags: common

- name: Common | Ensure ~/bin exists
  file:
    path: /home/vagrant/bin
    state: directory
    owner: vagrant
    mode: '755'

- name: Common | Add the ~/bin to the path
  lineinfile: dest=/home/vagrant/.profile state=present line='export PATH="$PATH:$HOME/bin"'
  tags: common

- name: Common | Add the project's vendor/bin to the path
  lineinfile: dest=/home/vagrant/.profile state=present line='export PATH="$PATH:/var/www/{{ hostname }}/vendor/bin"'
  tags: common

- name: Common | Change directory into the project root on login
  lineinfile: dest=/home/vagrant/.profile state=present line='cd /var/www/{{ hostname }}'
  tags: common
