---

- name: PHP | Get the installed PHP version
  command: php -r 'preg_match("/[0-9]+\.[0-9]/", phpversion(), $matches); echo current($matches);'
  register: php_version

- name: PHP | Check whether apache2, fpm, or cli configs exist
  shell: "ls /etc/php/{{ php_version.stdout }} | grep -E 'apache|cli|fpm'"
  register: installed_configs

- name: PHP | Adjust php.ini memory_limit
  become: true
  lineinfile:
    dest: "/etc/php/{{ php_version.stdout }}/{{ item }}/php.ini"
    regexp: ^memory_limit
    line: "memory_limit = {{ php_ini_memory_limit }}"
  with_items: "{{ installed_configs.stdout_lines }}"
  tags: PHP

- name: PHP | Adjust php.ini memory_limit for CLI
  become: true
  lineinfile:
    dest: "/etc/php/{{ php_version.stdout }}/cli/php.ini"
    regexp: ^memory_limit
    line: memory_limit = -1

- name: PHP | Enable PHP error reporting
  become: true
  lineinfile:
    dest: "/etc/php/{{ php_version.stdout }}/{{ item }}/php.ini"
    regexp: ^error_reporting
    line: "error_reporting = {{ php_ini_error_reporting }}"
  with_items: "{{ installed_configs.stdout_lines }}"
  tags: PHP

- name: PHP | Enable PHP error display
  become: true
  lineinfile:
    dest: "/etc/php/{{ php_version.stdout }}/{{ item }}/php.ini"
    regexp: ^display_errors
    line: "display_errors = {{ php_ini_display_errors }}"
  with_items: "{{ installed_configs.stdout_lines }}"
  tags: PHP

- name: PHP | Adjust php.ini upload_max_filesize
  become: true
  lineinfile:
    dest: "/etc/php/{{ php_version.stdout }}/{{ item }}/php.ini"
    regexp: ^upload_max_filesize
    line: "upload_max_filesize = {{ php_ini_upload_max_filesize }}"
  with_items: "{{ installed_configs.stdout_lines }}"
  tags: PHP

- name: PHP | Adjust php.ini post_max_size
  become: true
  lineinfile:
    dest: "/etc/php/{{ php_version.stdout }}/{{ item }}/php.ini"
    regexp: ^post_max_size
    line: "post_max_size = {{ php_ini_post_max_size }}"
  with_items: "{{ installed_configs.stdout_lines }}"
  tags: PHP
