---

- name: Drupal Check | Install drupal-check
  get_url:
    url: https://github.com/mglaman/drupal-check/releases/download/1.0.9/drupal-check.phar
    dest: /home/vagrant/bin/drupal-check
    mode: '0700'
    timeout: 1800
  tags: drupal-check

# Note: phing and drupal-check have mutually exclusive requirements.
# It'd be better to add drupal-check as a dependency of the drupal project
# rather than as part of the virtual environment, but this will have to do for
# now. Also note, drupal-check is added as part of the-build so it is available
# to CircleCI.
