---
- hosts: all
  vars:
    timezone: America/Chicago
    mysql_root_pass: root
    project_web_root: web
    solr_enabled: false
    https_enabled: false
    system_packages: []
  roles:
    - { role: common }
    - { role: php }
    - { role: vhost }
    - { role: https }
    - { role: solr }
    - { role: drupal-check }
    - { role: gulp }
    - { role: elnebuloso.nvm,
        nvm_user: "vagrant",
        become: true,
      }
