---
- hosts: all
  vars:
    timezone: America/Chicago
    mysql_root_pass: root
    project_web_root: web
    solr_enabled: false
    https_enabled: false
    system_packages: ["python-mysqldb"]
  roles:
    - { role: common }
    - { role: php }
    - { role: vhost }
    - { role: fordschool-d7 }
    - { role: solr }
    - { role: drupal-check }
    - { role: drush }
    - { role: gulp }
    - { role: elnebuloso.nvm,
        nvm_user: "vagrant",
        become: true,
    }
