---
- name: Install Apache vhost
  become: true
  template: src=drupal8-skeleton.conf dest=/etc/apache2/sites-available/{{ hostname }}.conf
  tags: vhost

- name: Stat {{ hostname }} vhost conf
  stat: path=/etc/apache2/sites-enabled/{{ hostname }}.conf
  register: drupal8_vhost_exists
  tags: vhost

- name: Enable {{ hostname }} vhost
  become: true
  shell: /usr/sbin/a2ensite {{ hostname }}
  when: drupal8_vhost_exists.stat.exists == False
  tags: vhost

- name: Replace apache user
  become: true
  lineinfile: dest=/etc/apache2/envvars
              regexp='export APACHE_RUN_USER=www-data' line='export APACHE_RUN_USER=vagrant'
              state=present
  tags: vhost

- name: Replace apache group
  become: true
  lineinfile: dest=/etc/apache2/envvars
              regexp='export APACHE_RUN_GROUP=www-data' line='export APACHE_RUN_GROUP=vagrant'
              state=present
  tags: vhost

- name: Restart Apache
  become: true
  service: name=apache2 state=restarted
  tags: vhost
